package de.tzeidler.myvideos.gui;

import de.tzeidler.myvideos.GENRES;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import static java.util.Locale.filter;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Toni Zeidler
 */
public class MyVideoMainFrame extends javax.swing.JFrame {

    // Plus Objects 
    private static Connection conn;
    private static Statement stmt;
    private static ResultSet rs;
    
    /**
     * Creates new form MyVideoMainFrame
     */
    public MyVideoMainFrame() {
        initComponents();
        // Plus Method
        tableData();
        jComboBox_genres.setModel(new DefaultComboBoxModel<>(GENRES.values()));
    }
    
//------------ My Methods
    
    public void tableData(){
        MyVideoMainFraimUtil utils = new MyVideoMainFraimUtil();
        DefaultTableModel model = new DefaultTableModel();
        model = utils.getListe();
        jTable_myvideo.setModel(model);
    }
    
    public void insertData(){
        MyVideoMainFraimUtil utils = new MyVideoMainFraimUtil();
        //utils.insertVideo(jTextField_title.getText(), "D:\\Zorro-1975-poster.jpg", 
        utils.insertVideo(jTextField_title.getText(), "../img/Zorro-1975-poster.jpg",
                GENRES.Western, 5, jTextArea_info.getText(), jTextArea_videopath.getText());
    }
    
    public void deliteData(){
        MyVideoMainFraimUtil utils = new MyVideoMainFraimUtil();
        utils.deleteVideo(Integer.parseInt(jTextField_id.getText()));
    }
    
    public void changeData(){
        MyVideoMainFraimUtil utils = new MyVideoMainFraimUtil();
        //utils.updatetVideo(Integer.parseInt(jTextField_id.getText()),jTextField_title.getText(), "D:\\Zorro-1975-poster.jpg", 
        utils.updatetVideo(Integer.parseInt(jTextField_id.getText()),jTextField_title.getText(), "../img/Zorro-1975-poster.jpg", 
                GENRES.Western, 5, jTextArea_info.getText(), jTextArea_videopath.getText());
    }
    
//------------ My Methods The End

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser_image = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_myvideo = new javax.swing.JTable();
        jPanel_image = new javax.swing.JPanel();
        jLabel_image = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_title = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_stars = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_genres = new javax.swing.JComboBox<>();
        jButton_exit = new javax.swing.JButton();
        jButton_refresh = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_change = new javax.swing.JButton();
        jButton_insert = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_info = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_videopath = new javax.swing.JTextArea();
        jButton_ichoosImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_myvideo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Titel 5", "Titel 6", "Titel 7"
            }
        ));
        jTable_myvideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_myvideoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_myvideo);

        jPanel_image.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel_imageLayout = new javax.swing.GroupLayout(jPanel_image);
        jPanel_image.setLayout(jPanel_imageLayout);
        jPanel_imageLayout.setHorizontalGroup(
            jPanel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_imageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_imageLayout.setVerticalGroup(
            jPanel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_imageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("id");

        jTextField_id.setEnabled(false);
        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jLabel3.setText("Title");

        jLabel4.setText("Info");

        jLabel5.setText("Genres");

        jLabel6.setText("Stars");

        jButton_exit.setText("Beenden");
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });

        jButton_refresh.setText("Aktualisieren");
        jButton_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshActionPerformed(evt);
            }
        });

        jButton_delete.setText("Löschen");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_change.setText("Ändern");
        jButton_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_changeActionPerformed(evt);
            }
        });

        jButton_insert.setText("Einfügen");
        jButton_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertActionPerformed(evt);
            }
        });

        jLabel7.setText("Wo habe ich die zuletzt hingestellt ?");

        jTextArea_info.setColumns(20);
        jTextArea_info.setRows(5);
        jScrollPane2.setViewportView(jTextArea_info);

        jTextArea_videopath.setColumns(20);
        jTextArea_videopath.setRows(5);
        jScrollPane3.setViewportView(jTextArea_videopath);

        jButton_ichoosImage.setText("...");
        jButton_ichoosImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ichoosImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_ichoosImage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_title)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jComboBox_genres, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(49, 49, 49))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextField_stars, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel7))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jButton_insert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_change)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_exit))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_genres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_stars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addComponent(jPanel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_exit)
                    .addComponent(jButton_refresh)
                    .addComponent(jButton_delete)
                    .addComponent(jButton_change)
                    .addComponent(jButton_insert)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_ichoosImage)))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jButton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertActionPerformed
        insertData();
    }//GEN-LAST:event_jButton_insertActionPerformed

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_exitActionPerformed

    private void jTable_myvideoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_myvideoMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable_myvideo.getModel();
        int i = jTable_myvideo.getSelectedRow();
        if(i == -1){
            JOptionPane.showMessageDialog(this, "Selektiere eine Zeille");
        }else{
            jTextField_id.setText(jTable_myvideo.getValueAt(i, 0).toString());
            jTextField_title.setText(jTable_myvideo.getValueAt(i, 1).toString());
            // image jTextField_title.setText((String) jTable_myvideo.getValueAt(i, 2));
            jComboBox_genres.setSelectedItem(jTable_myvideo.getValueAt(i, 3).toString());
            jTextField_stars.setText(jTable_myvideo.getValueAt(i, 4).toString());
            jTextArea_info.setText(jTable_myvideo.getValueAt(i, 5).toString());
            jTextArea_videopath.setText(jTable_myvideo.getValueAt(i, 6).toString());
        }
    }//GEN-LAST:event_jTable_myvideoMouseClicked

    private void jButton_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_changeActionPerformed
        changeData();
    }//GEN-LAST:event_jButton_changeActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        deliteData();
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshActionPerformed
        tableData();
    }//GEN-LAST:event_jButton_refreshActionPerformed

    private void jButton_ichoosImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ichoosImageActionPerformed
        jFileChooser_image.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = jFileChooser_image.showOpenDialog(this);
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
        "Images", "jpg", "gif", "png");
        jFileChooser_image.setFileFilter(filter);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jFileChooser_image.getSelectedFile();
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());
            // load from file
            //  Image image = null;
            try 
            {  
                BufferedImage bi = ImageIO.read(selectedFile);
                //JLabel pictureLabel = new JLabel();
                jLabel_image.setIcon(new ImageIcon(bi));
                jPanel_image.add(jLabel_image);
                if((jPanel_image.getWidth() ==0)&&(jPanel_image.getHeight()==0))
                    System.out.println("yes");
                    jPanel_image.add(jLabel_image);
               //bi.getData();
              /* image = ImageIO.read(fileToOpen);
                InputStream is = new BufferedInputStream(
                          new FileInputStream("image.gif"));
                      image = ImageIO.read(is);
                      JLabel label = new JLabel(new ImageIcon(image));
                      j.add(label);
                System.out.println("hello ");*/
               // BufferedImage br=new BufferedImage(new FileReader(fileToOpen));
            }  
            catch(Exception exception)  
            {  
             System.out.println("Problem occour when to open the file");  
            }  
        }
        if (result == JFileChooser.CANCEL_OPTION) {
            
        }
    }//GEN-LAST:event_jButton_ichoosImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyVideoMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyVideoMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyVideoMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyVideoMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyVideoMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_change;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_ichoosImage;
    private javax.swing.JButton jButton_insert;
    private javax.swing.JButton jButton_refresh;
    private javax.swing.JComboBox<GENRES> jComboBox_genres;
    private javax.swing.JFileChooser jFileChooser_image;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JPanel jPanel_image;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_myvideo;
    private javax.swing.JTextArea jTextArea_info;
    private javax.swing.JTextArea jTextArea_videopath;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_stars;
    private javax.swing.JTextField jTextField_title;
    // End of variables declaration//GEN-END:variables
}
